### ISSUE TITLE
[APP][Unexpected ERROR]:Heatmap_plot error

### ISSUE THREAD

**Issue by SillaLIN** [ventolab/CellphoneDB#110]
Hi,
In previous, I do appreciate your fast response about running statistical analysis.
From the successful statistical analysis results, I tried to draw a heatmap plot of cellphoneDB.

However, unexpected error occurs and I am unable to solve this issues. The detail of error is as follow.

(cellphonedb) C:\Users\95369>cellphonedb plot heatmap_plot meta02.txt
Warning message:
package 'methods' was built in R 3.6.3
During startup - Warning messages:
1: 'datasets'R3.6.3
2: 'utils'R3.6.3
3: 'grDevices'R3.6.3
4: 'graphics'R3.6.3
5: 'stats'R3.6.3
From cffi callback <function _consolewrite_ex at 0x0000021EBF921438>:
Traceback (most recent call last):
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 29: invalid start byte
R[write to console]: In addition:
R[write to console]: Warning message:

From cffi callback <function _consolewrite_ex at 0x0000021EBF921438>:
Traceback (most recent call last):
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\callbacks.py", line 133, in _consolewrite_ex
    s = conversion._cchar_to_str_with_maxlen(buf, n, _CCHAR_ENCODING)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 138, in _cchar_to_str_with_maxlen
    s = ffi.string(c, maxlen).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb3 in position 0: invalid start byte
[ ][APP][20/04/23-20:30:54][ERROR] Unexpected error
Traceback (most recent call last):
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\cellphonedb\src\api_endpoints\terminal_api\plot_terminal_api_endpoints\plot_terminal_commands.py", line 78, in heatmap_plot
    pvalue=pvalue)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\cellphonedb\src\plotters\r_plotter.py", line 38, in wrapper
    return f(*args, **kwargs, robjects=robjects, r_runtime_error=RRuntimeError)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\cellphonedb\src\plotters\r_plotter.py", line 60, in heatmaps_plot
    robjects.r.source(os.path.join(this_file_dir, 'R/plot_heatmaps.R'))
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\robjects\functions.py", line 209, in __call__
    .__call__(*args, **kwargs))
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\robjects\functions.py", line 131, in __call__
    res = super(Function, self).__call__(*new_args, **new_kwargs)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 45, in _
    cdata = function(*args, **kwargs)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface.py", line 817, in __call__
    raise embedded.RRuntimeError(_rinterface._geterrmessage())
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\_rinterface_capi.py", line 439, in _geterrmessage
    res = _string_getitem(res, 0)
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\_rinterface_capi.py", line 287, in _string_getitem
    conversion._R_ENC_PY[openrlib.rlib.Rf_getCharCE(elt)]
  File "C:\Users\95369\.conda\envs\cellphonedb\lib\site-packages\rpy2\rinterface_lib\conversion.py", line 132, in _cchar_to_str
    s = ffi.string(c).decode(encoding)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb2 in position 29: invalid start byte

It seems that RRuntimeError is the main reason. Can you help me? Looking forward to your early reply, thank you!!

**Comment by prete** [comment]
Hi, you should try using ktplots](https://ktplotspy.readthedocs.io/en/latest/notebooks/tutorial.html) to visualize your results. Also, it look like using an older version of CellPhoneDB, I highly recommend you update to the latest version (`pip update -U cellphonedb`) to benefit from newer features.
