### ISSUE TITLE
error report during running CellphoneDB

### ISSUE THREAD

**Issue by sadiexiaoyu** [ventolab/CellphoneDB#12]
I am trying to run Cellphonedb, and got the following error report, 
could anyone give any suggestion?
Thanks in advance!

[ ][APP][25/01/22-10:34:23][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][25/01/22-10:34:23][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][25/01/22-10:34:23][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][25/01/22-10:34:23][INFO] Using custom database at /BIGDATA2/sysu_lygu_1/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][25/01/22-10:34:23][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][25/01/22-10:34:23][INFO] Launching Method _set_paths
[ ][APP][25/01/22-10:34:23][INFO] Launching Method _load_meta_counts
[ ][APP][25/01/22-10:36:16][INFO] Launching Method _check_counts_data
[ ][CORE][25/01/22-10:36:16][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][25/01/22-10:36:16][INFO] Launching Method _counts_validations
[ ][CORE][25/01/22-10:36:17][INFO] Launching Method get_interactions_genes_complex
[ ][CORE][25/01/22-10:36:18][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:4 Precision:3
[ ][CORE][25/01/22-10:36:26][INFO] Running Real Analysis
[ ][APP][25/01/22-10:36:26][ERROR] Unexpected error
Traceback (most recent call last):
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 143, in na_arithmetic_op
    result = expressions.evaluate(op, left, right)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 233, in evaluate
    return _evaluate(op, op_str, a, b)  # type: ignore
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 119, in _evaluate_numexpr
    result = _evaluate_standard(op, op_str, a, b)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 131, in statistical_analysis
    LocalMethodLauncher(cpdb_app.create_app(verbose, database)). \
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 62, in cpdb_statistical_analysis_local_method_launcher
    self.cellphonedb_app.method.cpdb_statistical_analysis_launcher(
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 95, in cpdb_statistical_analysis_launcher
    cpdb_statistical_analysis_method.call(meta,
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_method.py", line 27, in call
    cpdb_statistical_analysis_complex_method.call(meta.copy(),
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_complex_method.py", line 70, in call
    real_mean_analysis = cpdb_statistical_analysis_helper.mean_analysis(interactions_filtered,
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py", line 361, in mean_analysis
    columns=(pd.Series(cluster1_names) + separator + pd.Series(cluster2_names)).values)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/common.py", line 65, in new_method
    return method(self, other)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/__init__.py", line 343, in wrapper
    result = arithmetic_op(lvalues, rvalues, op)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 190, in arithmetic_op
    res_values = na_arithmetic_op(lvalues, rvalues, op)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 150, in na_arithmetic_op
    result = masked_arith_op(left, right, op)
  File "/BIGDATA2/sysu_lygu_1/.conda/envs/cpdb/lib/python3.8/site-packages/pandas/core/ops/array_ops.py", line 112, in masked_arith_op
    result[mask] = op(xrav[mask], y)
numpy.core._exceptions._UFuncNoLoopError: ufunc 'add' did not contain a loop with signature matching types (dtype('<U21'), dtype('<U21')) -> dtype('<U21')

**Comment by prete** [comment]
Hi @sadiexiaoyu thank you for using CellPhoneDB!
The error can be either an encoding issue with your input file or that there are actually some unexpected values inside of it, particularly column names or a custom separator. To further assist you we'd need to have a look at your input file and the command you used to launch CellPhoneDB.

**Comment by sadiexiaoyu** [comment]
> Thanks for the reply!
I used the output gene name from Cellranger as the column 1 in the count_data.txt as the input file. However, I noticed that it says that --counts-data: [ensembl | gene_name | hgnc_symbol] Type of gene identifiers in the counts data. So should use ensembl ID, or gene name or hgnc symbol. 
My gene names are like this:
PUSL1
INTS11
AL139287.1
CPTP
TAS1R3
DVL1
MXRA8
AURKAIP1
CCNL2
MRPL20-AS1
MRPL20
AL391244.2
ANKRD65
AL391244.1
TMEM88B
LINC01770
VWA1
ATAD3C
ATAD3B
ATAD3A
TMEM240
SSU72
AL645728.1
FNDC10
AL691432.4
AL691432.2
MIB2
MMP23B
CDK11B
FO704657.1
SLC35E2B
CDK11A
SLC35E2A
NADK
GNB1
AL109917.1
CALML6
TMEM52
CFAP74
AL391845.2
GABRD
PRKCZ
AL590822.2
Some of which are not Ensembl gene name (since I cannot find them in Ensembl database, such as AL391845.2, AL590822.2 etc.). Could you give me any suggestion about how to deal with this kind of data?

**Comment by nzhang89** [comment]
I also encountered this error. In my case, all the cell types are numbers (e.g. 1, 2, 3, etc.) I fixed the error by changing them to characters (e.g. 1 => cluster_1). Hope it helps.

**Comment by sadiexiaoyu** [comment]
Yes, it works! Thank you!

**Comment by YUE-Dr** [comment]
> I also encountered this error. In my case, all the cell types are numbers (e.g. 1, 2, 3, etc.) I fixed the error by changing them to characters (e.g. 1 => cluster_1). Hope it helps.

Thanks, re-name the cell-type and then it works,
