### ISSUE TITLE
No CellPhoneDB interacions found in this input

### ISSUE THREAD

**Issue by danli349** [ventolab/CellphoneDB#14]
I am trying to use CellPhoneDB to analyze mouse data.
I got the following error report when I use CellPhoneDB,
could anyone give any suggestion?
Thanks!

```
 cellphonedb method statistical_analysis \
> ETV4_meta.tsv \
> ETV4.h5ad \
> --output-path=./statistical_analysis \
> --counts-data hgnc_symbol \
> --iterations=10 \
> --threads=2
[ ][APP][03/02/22-14:14:47][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][03/02/22-14:14:47][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][03/02/22-14:14:47][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][03/02/22-14:14:47][INFO] Using custom database at /home/dan/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][03/02/22-14:14:47][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][03/02/22-14:14:47][INFO] Launching Method _set_paths
[ ][APP][03/02/22-14:14:47][INFO] Launching Method _load_meta_counts
[ ][APP][03/02/22-14:14:54][INFO] Launching Method _check_counts_data
[ ][CORE][03/02/22-14:14:54][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][03/02/22-14:14:54][INFO] Launching Method _counts_validations
[ ][CORE][03/02/22-14:14:54][INFO] Launching Method get_interactions_genes_complex
[ ][CORE][03/02/22-14:14:58][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:10 Debug-seed:-1 Threads:2 Precision:3
[ ][APP][03/02/22-14:14:59][ERROR] Unexpected error
Traceback (most recent call last):
  File "/home/dan/miniconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 150, in statistical_analysis
    debug,
  File "/home/dan/miniconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 75, in cpdb_statistical_analysis_local_method_launcher
    output_path
  File "/home/dan/miniconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 111, in cpdb_statistical_analysis_launcher
    output_path)
  File "/home/dan/miniconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_method.py", line 43, in call
    output_path
  File "/home/dan/miniconda3/envs/cpdb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_complex_method.py", line 57, in call
    raise NoInteractionsFound()
cellphonedb.src.core.exceptions.NoInteractionsFound.NoInteractionsFound: No CellPhoneDB interacions found in this input.
```

**Comment by luzgaral** [comment]
Hi,

Thanks for using CellphoneDB.

Could you give us more information about your input? 
Please note that CellphoneDB database is designed for human data, only human identifiers are accepted. 

Best

Luz

**Comment by danli349** [comment]
Hi Luz
Can we update the CellphoneDB database for mouse data?
My `ETV4_meta.tsv` is generated following the tutorial: https://github.com/ventolab/CellphoneDB/blob/master/notebooks/0_prepare_your_data_from_anndata.ipynb 
The `ETV4.h5ad` is generated by `anndata.AnnData.write`.

Thanks a lot
Dan
