### ISSUE TITLE
Error while using plotting functions 

### ISSUE THREAD

**Issue by aditisk** [ventolab/CellphoneDB#19]
Hello CellphoneDB team,

I am running into an error while using any plotting function. The error message is pasted below, please let me know how I can get past this issue.

Thanks.

(cpdb_fangping) [adk85@login0b IS1]$ cellphonedb plot dot_plot
[ ][APP][01/03/22-10:47:26][ERROR] Unexpected error
Traceback (most recent call last):
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/cellphonedb/src/api_endpoints/terminal_api/plot_terminal_api_endpoints/p                       lot_terminal_commands.py", line 33, in dot_plot
    r_plotter.dot_plot(means_path=means_path,
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/cellphonedb/src/plotters/r_plotter.py", line 36, in wrapper
    from rpy2 import robjects
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/rpy2/robjects/__init__.py", line 27, in <module>
    from . import vectors
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/rpy2/robjects/vectors.py", line 13, in <module>
    import jinja2
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/jinja2/__init__.py", line 12, in <module>
    from .environment import Environment
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/jinja2/environment.py", line 25, in <module>
    from .defaults import BLOCK_END_STRING
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/jinja2/defaults.py", line 3, in <module>
    from .filters import FILTERS as DEFAULT_FILTERS  # noqa: F401
  File "/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/jinja2/filters.py", line 13, in <module>
    from markupsafe import soft_unicode
ImportError: cannot import name 'soft_unicode' from 'markupsafe' (/ihome/rferris/jic115/.conda/envs/cpdb_fangping/lib/python3.8/site-packages/markupsafe/__i                       nit__.py)

**Comment by swemeshy** [comment]
Hi, I had this same issue. I fixed it by installing an earlier version of markupsafe:

`pip install markupsafe==2.0.1`
