### ISSUE TITLE
Issue Title: ImportError in CellPhoneDB - Cannot Import main

### ISSUE THREAD

**Issue by ArzooShamoon** [ventolab/CellphoneDB#207]
I'm encountering an ImportError when trying to run CellPhoneDB commands in my conda environment. The error message indicates that cellphonedb cannot import the main module from the package.

I have tried 

conda create -n cpdb_env python=3.8
conda activate cpdb_env
pip install cellphonedb

cpdb_env) ashamoon@c37:/projects/mpn/Arzoo/Fleischhauer_lab/Integrated_ScRNA_analysis/Sample1234/CellPhoneDB$ cellphonedb method analysis test_meta.txt test_counts.txt 
Traceback (most recent call last):
  File "/homes/ashamoon/mambaforge/envs/renv/bin/cellphonedb", line 2, in <module>
    from cellphonedb import main
ImportError: cannot import name 'main' from 'cellphonedb' (/homes/ashamoon/mambaforge/envs/renv/envs/cpdb_env/lib/python3.8/site-packages/cellphonedb/__init__.py

(cpdb_env) ashamoon@c37:/projects/mpn/Arzoo/Fleischhauer_lab/Integrated_ScRNA_analysis/Sample1234/CellPhoneDB$ cellphonedb --help
Traceback (most recent call last):
  File "/homes/ashamoon/mambaforge/envs/renv/bin/cellphonedb", line 2, in <module>
    from cellphonedb import main
ImportError: cannot import name 'main' from 'cellphonedb' (/homes/ashamoon/mambaforge/envs/renv/envs/cpdb_env/lib/python3.8/site-packages/cellphonedb/__init__.py)

**Comment by cakirb** [comment]
Hi @ArzooShamoon,

Thanks for using CellPhoneDB! Seems like you're using CLI commands, but they are discontinued after v5 (not sure how they are both recognised and cannot be found) so you should use CellPhoneDB from Python instead of running CellPhoneDB commands from terminal.

Hope this helps!

Best,
Batu
