### ISSUE TITLE
error when input with h5ad

### ISSUE THREAD

**Issue by notimenocall** [ventolab/CellphoneDB#29]
Hi,
Thanks for the great tool!
I installed v3 recently and am trying to use h5ad as input. While input with txt or a 10x folder work, input with h5ad gives me the following error. Any help will be appreciated!
Xiao

Command used:
`cellphonedb method analysis hPBMC_meta.tsv hPBMC_test.h5ad`
Output:
`[ ][APP][21/04/22-02:53:42][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][21/04/22-02:53:42][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][21/04/22-02:53:42][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][21/04/22-02:53:42][INFO] Using custom database at /home/jovyan/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][21/04/22-02:53:42][INFO] Launching Method cpdb_analysis_local_method_launcher
[ ][APP][21/04/22-02:53:42][INFO] Launching Method _set_paths
[ ][APP][21/04/22-02:53:42][INFO] Launching Method _load_meta_counts
[ ][APP][21/04/22-02:53:42][ERROR] Unexpected error
Traceback (most recent call last):
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/anndata/_io/utils.py", line 177, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 527, in read_group
    EncodingVersions[encoding_type].check(
  File "/opt/conda/envs/cpdb/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 203, in analysis
    LocalMethodLauncher(cpdb_app.create_app(verbose,
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 103, in cpdb_analysis_local_method_launcher
    counts, meta = self._load_meta_counts(counts_filename, meta_filename)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 233, in _load_meta_counts
    counts = utils.read_data_table_from_file(os.path.realpath(counts_filename), index_column_first=True)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/utils/utils.py", line 28, in read_data_table_from_file
    return _read_h5ad(file)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/cellphonedb/utils/utils.py", line 116, in _read_h5ad
    adata = read_h5ad(path)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 421, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/opt/conda/envs/cpdb/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/opt/conda/envs/cpdb/lib/python3.8/site-packages/anndata/_io/utils.py", line 183, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.`

**Comment by notimenocall** [comment]
Hi Luz,
Thanks for your reply. I somehow cannot find the .h5ad example. I was able to run the pipeline successfully with a .h5ad from my colleague. But I cannot identify the difference between our h5ad (I checked layers, adata.X, var and etc.). Both our .h5ad were converted from Seurat objects to h5ad using sceasy. I also tried SeuratDisk-converted h5ad but didn't work.
Could you provide some info on what the pipeline looks for from the .h5ad so I can check?
Thanks much!
Best,
Xiao

**Comment by luzgaral** [comment]
Here the example https://github.com/ventolab/CellphoneDB/blob/master/in/endometrium_atlas_example/endometrium_example_counts.h5ad

**Comment by catsargent** [comment]
I am also getting this same error. 
```
[ ][CORE][05/12/22-15:32:11][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][05/12/22-15:32:11][INFO] Using custom database at /Users/sargent/.cpdb/releases/v4.0.0/cellphone.db
[ ][APP][05/12/22-15:32:11][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][05/12/22-15:32:11][INFO] Launching Method _set_paths
[ ][APP][05/12/22-15:32:11][INFO] Launching Method _load_meta_counts
[ ][APP][05/12/22-15:32:13][ERROR] Unexpected error
Traceback (most recent call last):
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/anndata/_io/utils.py", line 177, in func_wrapper
    return func(elem, *args, **kwargs)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 527, in read_group
    EncodingVersions[encoding_type].check(
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/enum.py", line 387, in __getitem__
    return cls._member_map_[name]
KeyError: 'dict'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 131, in statistical_analysis
    LocalMethodLauncher(cpdb_app.create_app(verbose, database)). \
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 54, in cpdb_statistical_analysis_local_method_launcher
    counts, meta = self._load_meta_counts(counts_filename, meta_filename)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 233, in _load_meta_counts
    counts = utils.read_data_table_from_file(os.path.realpath(counts_filename), index_column_first=True)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/cellphonedb/utils/utils.py", line 28, in read_data_table_from_file
    return _read_h5ad(file)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/cellphonedb/utils/utils.py", line 116, in _read_h5ad
    adata = read_h5ad(path)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/anndata/_io/h5ad.py", line 421, in read_h5ad
    d[k] = read_attribute(f[k])
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/functools.py", line 875, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/Users/sargent/miniconda3/envs/cpdb/lib/python3.8/site-packages/anndata/_io/utils.py", line 183, in func_wrapper
    raise AnnDataReadError(
anndata._io.utils.AnnDataReadError: Above error raised while reading key '/layers' of type <class 'h5py._hl.group.Group'> from /.
```

I checked the example h5ad linked to in the comment above and the object looks like this:
```
AnnData object with n_obs × n_vars = 1949 × 20975
    obs: 'sample_names', 'log2p1_count', 'percent_mito', 'n_genes', 'batch', 'StudyName', 'SampleID', 'DonorID', 'BiopsyType', 'Location', 'Binary Stage', 'Stage', 'Day', 'Women age', '10x kit', 'Treatment', 'Batch', 'lineage', 'cell_type', 'n_counts'
    var: 'gene_ids', 'n_cells'
```

This is the structure of my object:
```
AnnData object with n_obs × n_vars = 112981 × 36601
    obs: 'nCount_RNA', 'nFeature_RNA', 'samples', 'Sex', 'Study', 'Disease_State', 'Inflamed_State', 'percent.mt', 'doublet_scores', 'doublet_class', 'cells_id', 'color_samples', 'cell_type'
    var: 'vst.mean', 'vst.variance', 'vst.variance.expected', 'vst.variance.standardized', 'vst.variable'
    uns: 'samples_colors', 'Sex_colors', 'Study_colors', 'Disease_State_colors', 'Inflamed_State_colors', 'doublet_class_colors', 'color_samples_colors', 'cell_type_colors', 'log1p'
    obsm: 'X_harmony', 'X_pca', 'X_umap'
    layers: 'data', 'counts'
```

I thought perhaps I needed to strip of all layers apart from obs and var, so I saved a new object with just those (plus count data in .X), but I still got the same error. Any insight into what might be the issue? Anndata 0.80 was used for saving the object.

**Comment by catsargent** [comment]
I presume the issue is due to inompatibility of anndata versions. Anndata version 0.7.8 is installed with CellPhoneDb. Upgrading to version 0.8.0 caused other errors. I guess for now a workaround will be to export counts from the h5ad file but this is not ideal. 

It would be great if CPDB developers could confirm whether it is possible to use h5ad objects exported using anndata 0.8.0 with CPDB.

**Comment by QiangShiPKU** [comment]
> I presume the issue is due to incompatibility of anndata versions. Anndata version 0.7.8 is installed with CellPhoneDb. Upgrading to version 0.8.0 caused other errors. I guess for now a workaround will be to export counts from the h5ad file but this is not ideal.
> 
> It would be great if CPDB developers could confirm whether it is possible to use h5ad objects exported using anndata 0.8.0 with CPDB.

agree this. I update anndata to 0.8.0 although warning the incompatibility of h5py, and cellphonedb works when input with h5ad.
This may help https://github.com/scverse/anndata/issues/698
