### ISSUE TITLE
invalid entry in coordinates array 

### ISSUE THREAD

**Issue by anidj** [ventolab/CellphoneDB#32]
Hi,

I got this error. I don't understand why. This is how I generate the input files:
`writeMM(data@assays$RNA@data, 
        file = 'data_test/matrix.mtx')
# save gene and cell names
write(x =  rownames(data@assays$RNA@data), 
      file = "data_test/features.tsv")
write(x = colnames(data@assays$RNA@data), 
      file = "data_test/barcodes.tsv")`

It seems related to some cells because if I take a subset, it works. However, I cannot understand what is the problem. I checked for NA, I checked also if it could related to a sum equals to zero in columns or rows, but it wasn't the case. Do you have an idea about what is happening?

Thanks a lot for your help,

`[ ][APP][09/05/22-18:40:59][ERROR] Unexpected error                                                                                                            Traceback (most recent call last):                                                                                                                               File "C:\Users\adjedi\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\api_endpoints\terminal_api\method_terminal_api_endpoints\method_terminal_commands.py", line 150, in statistical_analysis                                                                                                                            debug,                                                                                                                                                       File "C:\Users\adjedi\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\local_launchers\local_method_launcher.py", line 75, in cpdb_statistical_analysis_local_method_launcher                                                                                                                                              output_path                                                                                                                                                  File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\method_launcher.py", line 111, in cpdb_statistical_analysis_launcher                                                                                                                                                                   output_path)                                                                                                                                                 File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_method.py", line 43, in call                  output_path                                                                                                                                                  File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 61, in call          clusters = cpdb_statistical_analysis_helper.build_clusters(meta, counts_filtered, complex_composition_filtered, skip_percent=False)                          File "C:\Users\adjedi\Anaconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_helper.py", line 141, in build_clusters       npg.aggregate(meta[CELL_TYPE].cat.codes, counts.values, func='mean', axis=1),                                                                                File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\numpy_groupies\aggregate_numba.py", line 441, in aggregate                                           return func(group_idx, a, size, fill_value, order, dtype, axis, **kwargs)                                                                                    File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\numpy_groupies\aggregate_numba.py", line 41, in __call__                                             iv = input_validation(group_idx, a, size=size, order=order, axis=axis, check_bounds=False)                                                                   File "C:\Users\x\Anaconda3\envs\cpdb\lib\site-packages\numpy_groupies\utils_numpy.py", line 249, in input_validation                                        mode='raise')                                                                                                                                                File "<__array_function__ internals>", line 6, in ravel_multi_index                                                                                          ValueError: invalid entry in coordinates array  `

**Comment by anidj** [comment]
Hi,

Just to let you know in case someone get the same problem. It came from the fact I had NA in my cell type annotation (in the meta file).

Best regards,
