### ISSUE TITLE
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

### ISSUE THREAD

**Issue by Zifeng-L** [ventolab/CellphoneDB#4]
Hi there, I tried to use cellphoneDB on my data (800kcells x 30k genes). It seemed something wrong with the analysis. 
The output is as follows. Is the dataset is too big for this analysis? How can I solve this problem?
```
[ ][APP][18/12/21-10:09:05][WARNING] Latest local available version is `v2.0.0`, using it
[ ][APP][18/12/21-10:09:05][WARNING] User selected downloaded database `v2.0.0` is available, using it
[ ][CORE][18/12/21-10:09:05][INFO] Initializing SqlAlchemy CellPhoneDB Core
[ ][CORE][18/12/21-10:09:05][INFO] Using custom database at /home/u21111240011/.cpdb/releases/v2.0.0/cellphone.db
[ ][APP][18/12/21-10:09:05][INFO] Launching Method cpdb_statistical_analysis_local_method_launcher
[ ][APP][18/12/21-10:09:05][INFO] Launching Method _set_paths
[ ][APP][18/12/21-10:09:06][INFO] Launching Method _load_meta_counts
[ ][APP][18/12/21-10:10:09][INFO] Launching Method _check_counts_data
[ ][CORE][18/12/21-10:10:09][INFO] Launching Method cpdb_statistical_analysis_launcher
[ ][CORE][18/12/21-10:10:09][INFO] Launching Method _counts_validations
[ ][CORE][18/12/21-10:10:10][INFO] Launching Method get_interactions_genes_complex
[ ][CORE][18/12/21-10:11:13][INFO] [Cluster Statistical Analysis] Threshold:0.1 Iterations:1000 Debug-seed:-1 Threads:30 Precision:3
[ ][CORE][18/12/21-10:13:24][INFO] Running Real Analysis
[ ][CORE][18/12/21-10:13:24][INFO] Running Statistical Analysis
[ ][APP][18/12/21-10:19:18][ERROR] Unexpected error
Traceback (most recent call last):
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/api_endpoints/terminal_api/method_terminal_api_endpoints/method_terminal_commands.py", line 150, in statistical_analysis
    debug,
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/local_launchers/local_method_launcher.py", line 75, in cpdb_statistical_analysis_local_method_launcher
    output_path
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/core/methods/method_launcher.py", line 111, in cpdb_statistical_analysis_launcher
    output_path)
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_method.py", line 43, in call
    output_path
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_complex_method.py", line 91, in call
    separator)
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/site-packages/cellphonedb/src/core/methods/cpdb_statistical_analysis_helper.py", line 486, in shuffled_analysis
    results = pool.map(statistical_analysis_thread, range(iterations))
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/multiprocessing/pool.py", line 268, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/multiprocessing/pool.py", line 657, in get
    raise self._value
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/multiprocessing/pool.py", line 431, in _handle_tasks
    put(task)
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/home/u21111240011/miniconda3/envs/cellphonedb/lib/python3.7/multiprocessing/connection.py", line 393, in _send_bytes
    header = struct.pack("!i", n)
struct.error: 'i' format requires -2147483648 <= number <= 2147483647

```

**Comment by Zifeng-L** [comment]
See https://github.com/Teichlab/cellphonedb/issues/136 .
Doing `conda install python=3.8` works for me.
