### ISSUE TITLE
Unexpected Error

### ISSUE THREAD

**Issue by Guy2Horev** [ventolab/CellphoneDB#45]
cellphonedb was installed under conda (Miniconda3) on windows server.
I tried to run the sample files and got the errors below.
Can you please advice?

[ ][CORE][29/06/22-21:37:57][INFO] Running Complex Prefilters
[ ][APP][29/06/22-21:37:59][ERROR] Unexpected error
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\api_endpoints\terminal_api\method_terminal_api_endpoints\method_terminal_commands.py", line 66, in statistical_analysis
    result_precision
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\local_launchers\local_method_launcher.py", line 55, in cpdb_statistical_analysis_local_method_launcher
    result_precision)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\method_launcher.py", line 62, in cpdb_statistical_analysis_launcher
    result_precision)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_method.py", line 41, in call
    result_precision)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 41, in call
    cells_names)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\cellphonedb\src\core\methods\cpdb_statistical_analysis_complex_method.py", line 416, in get_complex_significative
    complex_more_significative_protein = pd.Series(data='', index=complex_counts['name_complex'].drop_duplicates())
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\pandas\core\series.py", line 275, in __init__
    raise_cast_failure=True)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\pandas\core\series.py", line 4149, in _sanitize_array
    value, len(index), dtype)
  File "C:\ProgramData\Miniconda3\envs\cpdb\lib\site-packages\pandas\core\dtypes\cast.py", line 1201, in construct_1d_arraylike_from_scalar
    subarr = np.empty(length, dtype=dtype)
TypeError: Cannot interpret '<attribute 'dtype' of 'numpy.generic' objects>' as a data type

**Comment by Guy2Horev** [comment]
thanks for the prompt response, here is the information.

(base) C:\Users\Administrator>conda activate cpdb

(cpdb) C:\Users\Administrator>pip show pandas
Name: pandas
Version: 0.23.4
Summary: Powerful data structures for data analysis, time series, and statistics
Home-page: http://pandas.pydata.org
Author:
Author-email:
License: BSD
Location: c:\programdata\miniconda3\envs\cpdb\lib\site-packages
Requires: python-dateutil, numpy, pytz
Required-by: CellPhoneDB

(cpdb) C:\Users\Administrator>pip show numpy
Name: numpy
Version: 1.21.6
Summary: NumPy is the fundamental package for array computing with Python.
Home-page: https://www.numpy.org
Author: Travis E. Oliphant et al.
Author-email:
License: BSD
Location: c:\programdata\miniconda3\envs\cpdb\lib\site-packages
Requires:
Required-by: pandas

**Comment by prete** [comment]
I'm afraid those aren't the right ones for CellPhoneDB. 
Could you please try installing the compatible version explicitly: `pip install pandas==1.1.4 numpy==1.19.5` and then trying once more?

**Comment by Guy2Horev** [comment]
Thanks a lot, that resolved the problem.
I also got the warnings about R_HOME and R_USER which I managed to resolve by installing rpy as described here:
https://anaconda.zendesk.com/hc/en-us/articles/360023857134-Setting-up-rpy2-on-Windows
